### PR TITLE
eventbox issue

### PR DESCRIPTION
**Pull request by AntonWontonn**
added box shadow to event gallery box with correct color

### CODE REVIEW

**Comment by pondohoo** [comment]
upload a screenshot

**Comment by pondohoo** [comment]
assign issue 
image

**Comment by pondohoo** [comment]
assign yourself 
image

**Comment by AntonWontonn** [comment]
Screenshot 2024-10-21 100643

**Comment by AntonWontonn** [comment]
okay assigned myself

**Comment by pondohoo** [comment]
assign issue 
image

**Comment by AntonWontonn** [comment]
Screenshot 2024-10-21 203653

**Review by pondohoo — APPROVED** [review]

**Pull request merged**
